### ISSUE TITLE
Usage examples?

### ISSUE THREAD

**Issue by sxiii** [iamkamleshrangi/gaddress#1]
Can you provide any usage examples for this?

**Comment by iamkamleshrangi** [comment]
First login to your Facebook account and try to find cookie value from the network, then pass your query, country and facebook cookie to it. 
For example 
query: Eiffel tower Paris
country: Paris 
cookie: qwew2s95ldssr4s0be9dsisefdpr4s95kv9xem
Pass all value to function gaddress(query, country, cookie)

**Comment by sxiii** [comment]
Hi @iamkamleshrangi . Thanks for your explaination. The only thing I wonder what do you mean by "find the cookie value from the network". Facebook saves a dozen of cookies to my browser; to be exact; these:
![image](https://user-images.githubusercontent.com/575925/74155584-1f37db80-4c15-11ea-82d2-d44284ec0629.png)
Which one should I use? Or the cookie I need could be only obtained by sniffing network traffic? Can you please clarify. Thanks.

**Comment by iamkamleshrangi** [comment]
@sxiii 
To add cookie 
Please login to your Facebook account using firefox and select option web developer --> network. 
Once you get that. refresh your firefox browser. 
![download](https://user-images.githubusercontent.com/25166283/74156937-5c17c880-4c3d-11ea-8605-5be936ed3e2a.png)

In the request headers, you can get your cookie. 
Thanks 
Kamlesh

**Comment by sxiii** [comment]
@iamkamleshrangi yes; but there are like 10 values from facebook; the same as in the list before. I could view the same data using the cookie manager of the browser actually =)

That's what I've got there:
```
cookie: datr=3V5BXiFHhZ8ybFnrzu_nf_It; sb=715BXhm_la7PFJkA1y3AE_KU; c_user=100001135418993; xs=2%3A5IYVEazM7QBw8A%3A2%3A1581342492%3A10255%3A14503; fr=1zWrs1EpvT0ohIXLc.AWV0WGKiLwtu6QoJDdVTdWOlVoM.BeQV7v.fq.AAA.0.0.BeQV8b.AWUZP0Kw; spin=r.1001692905_b.trunk_t.1581342494_s.1_v.2_; act=1581343046283%2F1; presence=EDvF3EtimeF1581344443EuserFA21B01135418993A2EstateFDutF1581344443081CEchFDp_5f1B01135418993F0CC; wd=221x973
```

So, it's:
* datr
* sb
* c_user
* xs
* fr
* act
* presence
* wd

Which of these to take? ...

**Comment by iamkamleshrangi** [comment]
Your cookie value is: datr=3V5BXiFHhZ8ybFnrzu_nf_It; sb=715BXhm_la7PFJkA1y3AE_KU; c_user=100001135418993; xs=2%3A5IYVEazM7QBw8A%3A2%3A1581342492%3A10255%3A14503; fr=1zWrs1EpvT0ohIXLc.AWV0WGKiLwtu6QoJDdVTdWOlVoM.BeQV7v.fq.AAA.0.0.BeQV8b.AWUZP0Kw; spin=r.1001692905_b.trunk_t.1581342494_s.1_v.2_; act=1581343046283%2F1; presence=EDvF3EtimeF1581344443EuserFA21B01135418993A2EstateFDutF1581344443081CEchFDp_5f1B01135418993F0CC; wd=221x973

Please do not share your detail, Also made modifications to use API without facebook. 
Check now 
Regards 
Kamlesh

**Comment by sxiii** [comment]
Ahh I have to use all that? Okay. Thanks. @iamkamleshrangi
